config/routes.rb
Rails.application.routes.draw do
  resources :todo_items

  root 'todo_items#index'
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
	# before_create :default_values

 #  def default_values
 #    self.completed = false
 #    true
 #  end

  def complete?
    self.completed == true
  end

  def uncomplete
    update completed: false
  end

  def complete
    update completed: true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

	def index
		@list = TodoItem.all.order(:created_at)
	end

	def show
	end

	def create
		@item = TodoItem.create(item_params)
		redirect_to root_path
	end

	def update
		@item = TodoItem.find(params[:id])
		if @item.complete?
			@item.uncomplete
		else
			@item.complete
		end

		redirect_to root_path
	end

	def destroy
		TodoItem.find(params[:id]).destroy
		redirect_to root_path
	end


	private
	def item_params
		params.require(:todo_item).permit(:name)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todo_items/index.html.erb
<table>
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Status</th>
	</tr>

	<% @list.each do |item| %>
	<tr>
		<td><%= item.id %></td>
		<td><%= item.name %></td>
		<td><%= button_to item.completed.to_s, todo_item_path(item), method: :patch %></td>
		<td><%= button_to 'Delete', todo_item_path(item), method: :delete %></td>
	</tr>
	<% end %>
	<br>
</table>


<%= form_for :todo_item, url: todo_items_path do |f| %>
<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</p>

<p>
	<%= f.submit %>
</p>
<% end %>